### ISSUE TITLE
Plugin is dependent on android tools

### ISSUE THREAD

**Issue by sdetilly** [nbaztec/coveralls-jacoco-gradle-plugin#23]
It seems that we cannot use this plugin for pure (non-android) kotlin projects. The plugin fails with error "Could not find `com.android.tools.build:gradle`"

Will the plugin support non-android kotlin projects in the future?

**Comment by nbaztec** [comment]
Currently, the plugin relies on `com.android.tools` package to [identify](https://github.com/nbaztec/coveralls-jacoco-gradle-plugin/blob/main/src/main/kotlin/SourceReportParser.kt#L63) android source sets. 

As per the doc, including the google repository should do it.

```kotlin
buildscript {
    repositories {
        google()  // <--- include the google repository
        mavenCentral()
        jcenter()
    }
}
```

I would be more than happy to identify ways to not have this dependency, if possible.

**Comment by sdetilly** [comment]
Actually you are right, my problem was that I put the `google()` in the wrong `build.gradle` file. This is why the plugin could not access it 😓  Everything works fine now! Thank you 😄

**Comment by nhoughto** [comment]
could you do it via reflection instead? won't be type safe but would be basically the same but without the extra dependency?

**Comment by nhoughto** [comment]
Have PR to remove this, but in the interim you can fix by excluding it in your gradle file, since its only required during compile time
```
classpath ("com.github.nbaztec:coveralls-jacoco-gradle-plugin:1.2.6") {
            exclude group: "com.android.tools.build", module: "gradle"
        }
```

**Comment by nbaztec** [comment]
Plugin version `1.2.9` safely handles presence (or absence) of Android tools now, without the need to explicitly declare `google()` repository. Thanks @nhoughto for the initial PR.
