### ISSUE TITLE
No support for full range of coveralls api properties, like flag or parallel?

### ISSUE THREAD

**Issue by nhoughto** [nbaztec/coveralls-jacoco-gradle-plugin#25]
Seems like you support the majority of the properties of a 'job' object but not some, it would be nice to be able to specify the flag_name or parallel flags

https://docs.coveralls.io/api-reference

**Comment by nbaztec** [comment]
could you try with the newly published `v1.2.5`, the options are available from environment variables `COVERALLS_PARALLEL` (true/false) & `COVERALLS_FLAG_NAME` and described in the [README](https://github.com/nbaztec/coveralls-jacoco-gradle-plugin#usage).

**Comment by nhoughto** [comment]
Perfect, thanks!

Excellent Christmas present 🎉
