### ISSUE TITLE
Release v1.2.12 is not available through Gradle Plugin Portal

### ISSUE THREAD

**Issue by wdziemia** [nbaztec/coveralls-jacoco-gradle-plugin#46]
https://plugins.gradle.org/plugin/com.github.nbaztec.coveralls-jacoco

Gradle Plugin portal shows latest version as 1.2.11

![Screen Shot 2021-03-24 at 4 55 43 PM](https://user-images.githubusercontent.com/3921079/112382096-cebcf980-8cc1-11eb-94dd-fd2bbdc34cb9.png)

The release page for this repo shows the latest as 1.2.12

![Screen Shot 2021-03-24 at 4 56 26 PM](https://user-images.githubusercontent.com/3921079/112382194-edbb8b80-8cc1-11eb-98f7-3f09fb7d2f1e.png)

**Comment by nbaztec** [comment]
Thanks for reporting. Somehow gh action did not report a failure; fixed now.
