### ISSUE TITLE
Help/feature request. Supporting NODE_COVERALLS_DEBUG=1 environment variable for verbose mode.

### ISSUE THREAD

**Issue by kristoffer-paulsson** [nbaztec/coveralls-jacoco-gradle-plugin#53]
Hi I had a problem with coveralls not giving a failure when trying to upload my cover report via circlece.
I contacted coveralls.io by submitting an issue on their GitHub, however they assumed that I used their orb on circleci: coveralls/coveralls@1.0.6.

The thing is I use this jacoco coveralls plugin.

The asked me to activate verbose mode, read as follows:

```
Can you please invoke [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v) on your integration and share the full CI build log with debug output with me?

That will show the exact JSON you're trying to upload to the Coveralls API, as well as any errors encountered, by the API, or with the integration.

Assuming you're using the [Coveralls Orb for CircleCI](https://circleci.com/developer/orbs/orb/coveralls/coveralls), which uses the [node-coveralls](https://github.com/nickmerwin/node-coveralls) integration under the hood, here is how to invoke [verbose mode](https://docs.coveralls.io/troubleshooting#put-it-in-verbose--v):

Add the following environment variable to your .circleci/config.yml (or to env vars for your project) so that it's availabel to any/all coveralls steps:
NODE_COVERALLS_DEBUG=1
```

Obiously there is a verbose mode option on their API that I would like to be able to activate for debugging, https://circleci.com/developer/orbs/orb/coveralls/coveralls#commands

Could you please add this feature to the plugin, presumably I could make a small contribution in time and knowledge.

I would like the plugin to recognize the NODE_COVERALLS_DEBUG environment variable and enable verbose debugging reporting all JSON being communicated in both directions.

**Comment by nbaztec** [comment]
Hi, sorry it took so long. The plugin already has logs enabled via log4j, so if you set the logging level to `debug` you should see all the request payload and the resulting logs. On `info` you should have basic indication that the plugin is working. If some log message is missing that would've helped you debug this issue, please let me know.
