### ISSUE TITLE
Branch coverage not sent

### ISSUE THREAD

**Issue by Khaseyama** [nbaztec/coveralls-jacoco-gradle-plugin#67]
I was able to display Line coverage using coveralls-jacoco-gradle-plugin and circleCI.
But I don't see branch coverage.
Branch coverage was visible when I don't use coveralls-jacoco-gradle-plugin.
Can coveralls-jacoco-gradle-plugin be made to show branch coverage?

https://docs.coveralls.io/api-jobs-endpoint#:~:text=JSON%20OBJECT%3A%20SOURCE%20FILE

**Comment by nbaztec** [comment]
Hi, it seems that while JaCoCo supports branch coverage, it's not exactly translatable to what coveralls expects. I might take a look at it if I get some time, but it may not be trivial to implement an/or give the desired information on branch hits/misses.

**Comment by snackattas** [comment]
+1

**Comment by afinetooth** [comment]
Hi, @nbaztec, @snackattas.

From the coveralls.io side, let us know if we can help with the implementation.

In case it helps as a reference, I've attached an example of a Coveralls JSON-format Coverage Upload (the JSON file any Coveralls integration ultimately `POST`s to `https://coveralls.io/apio/v1/jobs`):

[Coveralls JSON-format Coverage Upload Example (4 files only) - 2024-03-18T100620.241.json](https://github.com/nbaztec/coveralls-jacoco-gradle-plugin/files/14640070/Coveralls.JSON-format.Coverage.Upload.Example.4.files.only.-.2024-03-18T100620.241.json)

In this example I've removed all but the first four (4) files in the `source_files` collection. The first two files have branch coverage stats; the second two do not. So you can see how that's represented.

Let me know if you have any questions.

**Comment by nbaztec** [comment]
@Khaseyama  I wanted to verify branch coverage before the `1.2.20` release once but didn't get around it. Could you please verify if it works for you now?

**Comment by Khaseyama** [comment]
@nbaztec 
> @Khaseyama I wanted to verify branch coverage before the `1.2.20` release once but didn't get around it. Could you please verify if it works for you now?

thank you, I'll check.
It may take a while.

**Comment by Khaseyama** [comment]
@nbaztec 
I have confirmed that branch coverage is displayed in Coveralls in ver1.2.20.
Thank you!
